before_script:
  - export http_proxy=http://10.82.4.10:8888/
  - export https_proxy=http://10.82.4.10:8888/
  - ruby -v
  - gem install bundler --no-ri --no-rdoc
  - bundle install

stages:
  - test

puppet:
  stage: test
  script:
    - rake metadata_lint
    - rake lint
    - rake spec SPEC_OPTS="--format documentation"
    - rake syntax:manifests
    - rake syntax:templates
  only:
    - development
    - staging
    - production
  tags:
    - puppet
